# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and build the site with Rake.
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: build-cv-pdf

on:
  repository_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: false  # Don't auto-checkout submodules
      - name: Update public bibliography submodule
        run: |
          git submodule update --init --recursive my-papers
          cd my-papers
          git branch -u origin/master master
          cd ..
          git submodule update --remote my-papers
      - name: Update private CV data submodule
        run: |
          git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git submodule update --init --recursive my-cv-data
          git submodule update --remote my-cv-data
      - name: Commit submodule updates
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Check if there are any changes to submodules
          if ! git diff --quiet --submodule; then
            echo "Submodule changes detected, committing..."
            git add my-papers my-cv-data
            git commit -m "Update submodules to latest commits

            🤖 Generated with GitHub Actions"
            git push
          else
            echo "No submodule changes to commit"
          fi
      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cv
          environment-file: environment.yml
          python-version: 3.12
          auto-activate-base: false
      - name: Generate Templates
        run: python generate_cv.py
      - name: Build CV PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Doss-Gollin-CV.tex
          args: "-bibtex-cond1 -pdfxe"
          post_compile: "latexmk -c"
          working_directory: "temp_output"
      - name: Build Biosketch PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Doss-Gollin-Biosketch.tex
          args: "-bibtex-cond1 -pdfxe"
          post_compile: "latexmk -c"
          working_directory: "temp_output"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp_output
          publish_branch: gh-pages
          keep_files: false
