# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and build the site with Rake.
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: build-cv-pdf

on:
  repository_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          persist-credentials: false
          submodules: true
      - name: Update bibliography
        run: |
          cd my-papers
          git branch -u origin/master master
          cd ..
          git submodule update --remote --recursive
      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cv
          environment-file: environment.yml
          python-version: ${{ matrix.python-verison }}
      - name: Generate Template
        run: python generate_cv.py
      - name: Build CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Doss-Gollin-CV.tex
          args: "-bibtex-cond1 -pdfxe"
          post_compile: "latexmk -c"
          working_directory: "docs"
      - name: Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/Doss-Gollin-CV.tex
          git add docs/Doss-Gollin-CV.pdf
          git add my-papers/
          git commit -m "update CV"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: True
