# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and build the site with Rake.
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: build-cv-pdf

on:
  repository_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: false  # Don't auto-checkout submodules
      - name: Update public bibliography submodule
        run: |
          git submodule update --init --recursive my-papers
          cd my-papers
          git branch -u origin/master master
          cd ..
          git submodule update --remote my-papers
      - name: Update private CV data submodule
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git submodule update --init --recursive my-cv-data
      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cv
          environment-file: environment.yml
          python-version: 3.12
      - name: Generate Templates
        run: python generate_cv.py
      - name: Generate Grants Excel
        run: python grants_to_excel.py
      - name: Build CV PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Doss-Gollin-CV.tex
          args: "-bibtex-cond1 -pdfxe"
          post_compile: "latexmk -c"
          working_directory: "temp_output"
      - name: Build Biosketch PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Doss-Gollin-Biosketch.tex
          args: "-bibtex-cond1 -pdfxe"
          post_compile: "latexmk -c"
          working_directory: "temp_output"
      - name: Copy CV to docs
        run: |
          cp temp_output/Doss-Gollin-CV.pdf docs/
          echo "✓ Copied CV PDF to docs/ for GitHub Pages"
      - name: Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/Doss-Gollin-CV.tex
          git add docs/Doss-Gollin-CV.pdf
          git add my-papers/
          git add my-cv-data/
          git commit -m "update CV"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: True
